name: Build Avium Kernel

on:
  workflow_dispatch:

env:
  CLANG_VERSION: r563880c
  KERNEL_SRC: https://github.com/AviumUI-Devices/kernel_oneplus_sdm845
  KERNEL_BRANCH: avium-16.2
  DEFCONFIG: vendor/sdm845-perf_defconfig

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 环境与源码
      run: |
        sudo apt-get update
        sudo apt-get install -y git bc build-essential flex bison libssl-dev libelf-dev clang lld llvm python3 zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
        git clone --depth=1 ${{ env.KERNEL_SRC }} -b ${{ env.KERNEL_BRANCH }} kernel

    - name: 下载 Clang
      run: |
        mkdir clang && cd clang
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-${{ env.CLANG_VERSION }}.tar.gz
        tar -xf clang-${{ env.CLANG_VERSION }}.tar.gz
        echo "CLANG_PATH=$(pwd)/bin" >> $GITHUB_ENV

    - name: 编译内核
      run: |
        cd kernel
        export PATH="${{ env.CLANG_PATH }}:$PATH"
        
        # KCFLAGS="-w" 用于忽略 Clang 21 对 4.19 内核代码的警告报错
        MAKE_ARGS="ARCH=arm64 LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- KCFLAGS=-w"
        
        make O=out $MAKE_ARGS ${{ env.DEFCONFIG }}
        make -j$(nproc --all) O=out $MAKE_ARGS

    - name: 上传镜像
      uses: actions/upload-artifact@v4
      with:
        name: Avium-Kernel
        path: |
          kernel/out/arch/arm64/boot/Image.gz-dtb
          kernel/out/arch/arm64/boot/dtbo.img
          